sudo: required
language: generic

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - george-edison55-precise-backports
    packages:
      - clang-3.8
      - g++-6
      - valgrind
      - cmake
      - cmake-data
      - libboost-dev

matrix:
    include:
    - os: linux
      env: CXX=clang++-3.8 CC=clang-3.8
    - os: linux
      env: CXX=g++-6 CC=gcc-6

git:
    submodules: false

before_install:
    - git submodule update --init --recursive

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_VERBOSE_MAKEFILE=ON .. && make
