sudo: required

language: cpp

matrix:
    include:
    - os: linux
      env: CXX=clang++-3.8 MEMCHECK=VALGRIND
      addons:
        apt:
          packages: ["clang-3.8", "valgrind", "cmake", "cmake-data"]
          sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.7", "george-edison55-precise-backports"]
    - os: linux
      env: CXX=g++-5 MEMCHECK=VALGRIND
      addons:
        apt:
          packages: ["g++-5", "valgrind", "cmake", "cmake-data"]
          sources: ["ubuntu-toolchain-r-test", "george-edison55-precise-backports"]

script:
    - mkdir build
    - cd build
    - cmake .. && make
