#!/bin/bash

set -euo pipefail

script_path="${BASH_SOURCE[0]}"
while [ -h "${script_path}" ]; do # resolve ${script_path} until the file is no longer a symlink
  script_dir="$( cd -P "$( dirname "${script_path}" )" >/dev/null 2>&1 && pwd )"
  script_path="$(readlink "${script_path}")"
  [[ ${script_path} != /* ]] && script_path="${script_dir}/${script_path}" # if ${script_path} was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
script_dir="$( cd -P "$( dirname "${script_path}" )" >/dev/null 2>&1 && pwd )"
repository_root_dir="${script_dir}/../"

function display_usage()
{
  echo "Usage: $0 [-g] [-c] [DIRECTORIES]"
  echo "Available options:"
  echo "-g              Generates .cmake-format file in root of repository based on default settings."
  echo "-c              Check only mode, files will not be formated. Fails on first error."
  echo "[DIRECTORIES]   Directories where to look for *.cmake and CMakeLists.txt files for style formating."
  exit 0
}

function echoerr
{
  echo "${@}" 1>&2;
}

function display_missing_style_file_error
{
  echoerr "Missing .cmake-format file in root of repository. Please use '-g' to generate one."
  exit 1
}

function display_missing_directories_error
{
  echoerr "Missing directories in input. Please provide directories where to search for *.cmake and CMakeLists.txt files."
  exit 1
}

function export_cmake_format_style_to_yaml_file
{
  if [ "$#" -eq 1 ]; then
    cmake-format --dump-config yaml > "${1}"
  else
    echoerr "export_cmake_format_style_to_yaml_file expects 1 arguments, provided ${#}"
    exit 1
  fi
}

function apply_cmake_format_style_on_file
{
  if [ "$#" -eq 1 ]; then
    cmake-format -i "${1}"
  else
    echoerr "apply_cmake_format_style_on_file expects 1 argument, provided ${#}"
    exit 1
  fi
}

function check_if_file_is_properly_formatted
{
  if [ "$#" -eq 1 ]; then
    cmake-format "${1}" | diff "${1}" - -u || ( echoerr "${1} is not properly formated"; exit 1 )
  else
    echoerr "check_if_file_is_properly_formatted expects 1 argument, provided ${#}"
    exit 1
  fi
}

function cmake_format_style_exists_in_dir
{
  if [ "$#" -eq 1 ]; then
    if [[ -f "${1}/.cmake-format.yaml" ]] || [[ -f "${1}/.cmake-format.json" ]] || [[ -f "${1}/.cmake-format.py" ]]; then
      return 0
    else
      return 1
    fi
  else
    echoerr "cmake_format_style_exists_in_dir expects 1 argument, provided ${#}"
    exit 1
  fi
}

command=apply_cmake_format_style_on_file
generated_style_file=false
check_flag=false
while getopts ":gc" option; do
  case "${option}" in
    g)
      export_cmake_format_style_to_yaml_file "${repository_root_dir}/.cmake-format.yaml"
      generated_style_file=true
      ;;
    c)
      command=check_if_file_is_properly_formatted
      check_flag=true
      ;;
    *)
      display_usage
      ;;
  esac
done
shift "$((OPTIND-1))"

#if user executed script without parameters print help
if [ "$#" -eq 0 ] && ! ${check_flag} && ! ${generated_style_file}; then
  display_usage
fi

#if check is not requested and directories are missing,
#but user generated style script should not fail
if [ "$#" -eq 0 ] && ! ${check_flag} && ${generated_style_file}; then
  exit 0
fi

#if check is requested and directories are missing, script should fail
if [ "$#" -eq 0 ] && ${check_flag}; then
  display_missing_directories_error
fi

if cmake_format_style_exists_in_dir "${repository_root_dir}"; then
  find "${@}" -type f          \
    \( -iname '*.cmake'        \
    -o -iname 'CMakeLists.txt' \
    \) -print0 | while IFS= read -r -d '' file; do "${command}" "${file}"; done
else
  display_missing_style_file_error
fi

exit 0
